#!/bin/bash
# This script is designed to be a Caja script
# Open a terminal at the current folder

# Pull out the current directory
CURR_DIR=${CAJA_SCRIPT_CURRENT_URI#file://}

# Open the terminal
mate-terminal --working-directory=$CURR_DIR &

